### PR TITLE
Fix a regression with required legacy versions (e.g. pytz>dev)

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2019954

### CODE REVIEW

**Comment by gordonmessmer** [comment]
I think we need some additional guards against legacy version with not equal, like "foobar != dev.*".  I'll work on that later today (hopefully).

(And maybe the right thing to do *is* to fail and ask the maintainer to fix the requirement.)

**Comment by hroncok** [comment]
See https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/457WHHCNN5UZ3G2ITACLVTMN2AVRYPJS/

**Comment by hroncok** [comment]
> I think we need some additional guards against legacy version with not equal, like "foobar != dev.*". I'll work on that later today (hopefully).

Have you ever got to that?

**Comment by gordonmessmer** [comment]
> Have you ever got to that?

No, not until today.  I hate to use the word overwhelmed, but if I'm honest, changing jobs this year has been overwhelming, and I haven't been able to commit time to this for a while.

I've got an alternative patch in #14 .  I'll try to put together PRs to sync up other users.  If you have suggestions for 14, then I'll adjust it and the PRs, too.

**Comment by hroncok** [comment]
Closing in favor of https://github.com/gordonmessmer/pyreq2rpm/pull/14

**Pull request closed without merging**
