### PR TITLE
Document unreasonable legacy comparisons

### PR DESCRIPTION
**Pull request by torsava**
Follow up for PR #7

### CODE REVIEW

**Comment by torsava** [comment]
@gordonmessmer what do you think?

**Comment by gordonmessmer** [comment]
I thought we should mention 321 as well, and the expectation that version 21.0 will remove support upstream.  #8 maybe?

**Comment by gordonmessmer** [comment]
Managed to flub that one.  I mean: I think #9 is more descriptive

**Comment by torsava** [comment]
> Managed to flub that one. I mean: I think #9 is more descriptive

Oh absolutely, I'll close this PR.

**Pull request closed without merging**
